# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    body_listener: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
    param_fetcher_listener: true
    access_denied_listener:
        json: true
    view:
        view_response_listener: 'force'
        formats:
            json: true

    exception:
        exception_controller: 'fos_rest.exception.controller:showAction'
        codes:
            Symfony\Component\HttpKernel\Exception\NotFoundHttpException: 404
            App\User\Exception\UserNotFoundException: 401
            App\User\Exception\UserDataNotFoundException: 400
            App\User\Exception\UserDataNotValidException: 422

