index:
    path: /api
    controller: App\Controller\HomeController::index

user_verify:
    path: /api/user/verify
    controller: App\Controller\UserController::verify
    methods: [POST]

find_username:
    path: /api/find/username/{username}
    controller: App\Controller\UserController::findUsername
    methods: [GET]
