App\Dto\UserDto:
#    constraints:
#        -   Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
#                fields: [username]
#                entityClass: App\Entity\User
#        -   Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
#                fields: [email]
#                entityClass: App\Entity\User
    properties:
        username:
            -   NotBlank:
            -   Length:
                    min: 3
                    max: 20
            -   Regex:
                    pattern: "/[a-zA-Z]+/"
            -   App\Validator\Constraints\UniqueUsername: ~

        email:
            -   NotBlank:
            -   Email:
            -   App\Validator\Constraints\UniqueEmail: ~

        password:
            -   Length:
                    min: 8
                    max: 20
        recaptcha:
            -   App\Validator\Constraints\ContainsValidRecaptcha: ~
